app.controller('NavController', require('./NavController'));
app.controller('ListaGommeController', require('./ListaGommeController'));
app.controller('NewGommaController', require('./NewGommaController'));
app.controller('ListaGommeByManufacturerController', require('./ListaGommeByManufacturerController'));
app.controller('LoginPageController', require('./LoginPageController'));
app.controller('AboutController', require('./AboutController'));
app.controller('InsertUserController', require('./InsertUserController'));
app.controller('searchContr', require('./searchContr'));
app.controller('InsertVehicleController',require('./InsertVehicleController'));
app.controller('ListVehicleController',require('./ListVehicleController'));
app.controller('ListaUsersController',require('./ListaUsersController'));